### ISSUE TITLE
[BUG line 201]

### ISSUE THREAD

**Issue by fjk8** [dnigamer/TeraboxUploaderCLI#6] opened 2024-05-21 20:52 UTC
Hello,

I have following error:

 python3 main.py
  File "/home/radio/Terabox-Uploader/main.py", line 201
    "path": f"{remoteloc + "/" + filename}",
                            ^
SyntaxError: f-string: expecting '}'

All fields in secrets configured, source dir in settings set to full linux path value, remote dir set to "/test"
Linux Ubuntu, curl and requirements installed.

**Comment by dnigamer** [comment] 2024-05-22 07:12
Hello! Thank you for reporting an issue on the project. 
After reviewing the code, I've noticed that the line you're referring to (201) doesn't contain the line of code that errored on your system. This means that you're probably using an older version of TeraboxUploadercCLI so, therefore, I recommend that you re-pull the repository from GitHub and retry to run the program.
The newer version doesn't need any modification to the configuration files, so you don't need to reconfigure anything else.

**Comment by fjk8** [comment] 2024-05-22 14:47
Hello, I'm repulled repo and now my output looks like this:

[2024-05-22 16:44:56] CURL        : Checking for curl...
[2024-05-22 16:44:56] CURL        : Curl is already installed or exists in the current folder.
Traceback (most recent call last):
  File "/home/fjk/TeraboxUploaderCLI/main.py", line 79, in <module>
    secrets = json.load(f)
  File "/usr/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 9 column 3 (char 448)

**Comment by dnigamer** [comment] 2024-05-22 14:53
That seems to be an issue with the secrets configuration file. Could you share how you have that file configured? If so, don't forget to remove the JS token value for privacy reasons.

**Comment by fjk8** [comment] 2024-05-22 15:05
{
  "jstoken": "xxx",
  "bdstoken": "9a85f407aa518c84dde343ab54103948",
  "cookies": {
    "csrfToken": "gmGdD8dlMEwvmdaSlSP-VLn3",
    "browserid": "yxKHOejYZCV0nboI3tra3pBLpnDERh0wzaxsj3gVF5AieCTY146rrAPwBn4=",
    "lang": "en",
    "ndus": "YvEQYCxteHuiqxvc2iRtKVnd6G9eVFGw2LSeA9mw",
    "ndut_fmt": "D2FDDBFE9116E3A4FA15F1220A57DBCCB8005AE3DE73641DD17FF7411AAE61DE",
  }
}

**Comment by dnigamer** [comment] 2024-05-22 15:16
Oh i see what it is. See the last line inside the cookies where you define the "ndut_fmt"? It shouldn't have the comma on the end of it. Like this:
``"ndut_fmt": "D2FDDBFE911...FF7411AAE61DE", <- remove the comma here`` 
\\/
``"ndut_fmt": "D2FDDBFE911...FF7411AAE61DE"``
Also, due to an recent update on the program, the "bdstoken" doesn't need to be set, so you can remove the whole line.
Try doing this and let me know if it's solved.

**Comment by fjk8** [comment] 2024-05-22 15:40
Hi, I'm also removed some commas from settings file and now its working great. Thanks for the help.
Do you plan to implement some overwrite/skip mechanism and recursive?

**Comment by dnigamer** [comment] 2024-05-22 15:52
You're welcome!
There is implemented a basic mechanism to ignore certain files, files extensions and folders altogether. About recursion, the algorithm that checks for the files on the directory given already checks every file on the folder, but I'm not sure about searching inside folders. This is because the program would need to have a feature to create directories on TeraBox cloud which I'm yet to implement.
Right now, the main focus is improving overall speed and memory usage on both encryption and chunk splitting, but that can surely be a new and critical feature to be added so thank you for the suggestion!

**Comment by fjk8** [comment] 2024-05-22 15:57
I'm tried to upload directory with subdirectories but without success. My goal it so make some emergency pictures backup there so I'm need lot of folders for sure. Now when file exist on cloud another one was uploaded with date on filename added. Thanks.

**Comment by dnigamer** [comment] 2024-05-22 16:11
I understand what you're trying to do now. I'll be adding that feature as soon as I can.
I'm aware of that problem of when the file already exists on the cloud, it creates a duplicate of it with a timestamp on the end. That's something I'm yet to implement, but still haven't got around to do it. Thank you!

**Closed as completed** 2024-05-22 20:37 UTC
